spring:
  application:
    name: quizmaker
  thymeleaf:
    cache: false
    encoding: UTF-8
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

app:
  admin:
    username: ${ADMIN_USERNAME:alice}
    # Change this password before going to production!
    password: '${ADMIN_PASSWORD:{bcrypt}$2a$12$QMyzlOhi1dYIbX3JxQPox.OE/BK0yFs66XoqCOYe8gbIZt7j3entS}'

logging:
  level:
    com.quizmaker: DEBUG
    org.springframework.security: DEBUG
