spring:
  application:
    name: quizmaker
  thymeleaf:
    cache: false
    encoding: UTF-8
  jackson:
    serialization:
      write-dates-as-timestamps: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

app:
  admin:
    username: admin
    # Cambia questa password prima di andare in produzione!
    password: "{bcrypt}$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lbu2"
    # password in chiaro: "changeme"

logging:
  level:
    com.quizmaker: DEBUG
    org.springframework.security: DEBUG
