# syntax=docker/dockerfile:1.2

ARG MAVEN_VERSION=3-sapmachine-21
ARG JAVA_VENDOR=azul/zulu-openjdk-alpine
ARG JAVA_VERSION=21-jre-headless-latest

# --- Stage 1: Builder ---
FROM maven:${MAVEN_VERSION} as builder

WORKDIR /application

RUN --mount=type=bind,source=pom.xml,target=pom.xml \
    --mount=type=bind,source=.m2/settings.xml,target=.m2/settings.xml \
    --mount=type=cache,target=/root/.m2 \
    mvn -s .m2/settings.xml -Dmaven.repo.local=/root/.m2/repository \
    dependency:go-offline -B

COPY . .

RUN --mount=type=cache,target=/root/.m2 \
    mvn -s .m2/settings.xml -Dmaven.repo.local=/root/.m2/repository \
    clean package -DskipTests -Dlicense.skip=true

# --- Stage 2: Runtime ---
FROM ${JAVA_VENDOR}:${JAVA_VERSION}
ARG UID=1010
ARG GID=1010

RUN addgroup --gid ${GID} -S spring && adduser --uid ${UID} -S spring -G spring
USER spring:spring

ARG JAR_FILE=/application/target/quizmaker*.jar
COPY --from=builder ${JAR_FILE} app.jar

ENV SPRING_PROFILES_ACTIVE dev

ENTRYPOINT ["java", "-XX:+UseContainerSupport", "-XX:MinRAMPercentage=35", "-XX:MaxRAMPercentage=70", "-jar", "/app.jar"]